nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173'] 
        allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization']
        max_age: 3600
    paths:
        '^/api/': # Activer CORS uniquement pour les routes commençant par /api/
            allow_origin: ['http://localhost:5173']
            allow_headers: ['*']
            allow_methods: ['*']
